"""add oauth account model

Revision ID: 5e31bd85d5bd
Revises: c7f9e2d3b4a1
Create Date: 2026-02-18 21:40:36.007537

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "5e31bd85d5bd"
down_revision = "c7f9e2d3b4a1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_oauth_account",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("provider_id", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "provider", "provider_id", name="uq_user_oauth_account_provider_provider_id"
        ),
    )
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(
            "password_hash", existing_type=sa.VARCHAR(length=100), nullable=True
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(
            "password_hash", existing_type=sa.VARCHAR(length=100), nullable=False
        )

    op.drop_table("user_oauth_account")
    # ### end Alembic commands ###
