"""add hidden field to grant

Revision ID: c7f9e2d3b4a1
Revises: b5c3a2d8e4f6
Create Date: 2026-02-12 00:00:00.000000

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "c7f9e2d3b4a1"
down_revision = "b5c3a2d8e4f6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("grant", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("hidden", sa.Boolean(), nullable=False, server_default=sa.false())
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("grant", schema=None) as batch_op:
        batch_op.drop_column("hidden")
    # ### end Alembic commands ###
