"""add description column

Revision ID: ce29726fd3cb
Revises: eb6dda4081ae
Create Date: 2026-01-30 09:26:42.075184

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "ce29726fd3cb"
down_revision = "eb6dda4081ae"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("grant", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("description", sa.String(length=1000), nullable=True)
        )
        batch_op.add_column(sa.Column("custom_fields", sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("grant", schema=None) as batch_op:
        batch_op.drop_column("custom_fields")
        batch_op.drop_column("description")

    # ### end Alembic commands ###
