"""add link to award from application model

Revision ID: f80615169851
Revises: 2f665539f34b
Create Date: 2026-03-19 20:00:20.456972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f80615169851'
down_revision = '2f665539f34b'
branch_labels = None
depends_on = None

FK_NAME = 'fk_application_award_id_award'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('award_justification', sa.String(length=1000), nullable=True))
        batch_op.add_column(sa.Column('award_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(FK_NAME, 'award', ['award_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    fk_name = next(
        (
            foreign_key["name"]
            for foreign_key in inspector.get_foreign_keys("application")
            if foreign_key["referred_table"] == "award"
            and foreign_key["constrained_columns"] == ["award_id"]
        ),
        FK_NAME,
    )

    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.drop_constraint(fk_name, type_='foreignkey')
        batch_op.drop_column('award_id')
        batch_op.drop_column('award_justification')

    # ### end Alembic commands ###
