"""add admin response to support messages

Revision ID: f9dea3dcfe50
Revises: 5f6b4d637211
Create Date: 2026-03-15 12:19:14.687680

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "f9dea3dcfe50"
down_revision = "5f6b4d637211"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("support_message", schema=None) as batch_op:
        batch_op.add_column(sa.Column("admin_response", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("answered_at", sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("support_message", schema=None) as batch_op:
        batch_op.drop_column("answered_at")
        batch_op.drop_column("admin_response")

    # ### end Alembic commands ###
