name: Terraform Infrastructure Provisioning & Configuration

on:
  push:
    branches: [ "infra-actions" ]
  workflow_dispatch:
    inputs:
      action:
        description: "Action to perform"
        required: true
        type: choice
        options:
          - plan
          - apply
          - destroy

permissions:
  id-token: write
  contents: read

env:
  ARM_USE_OIDC: true
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  TF_VAR_location: northeurope
  TF_VAR_acr_name: nausicaasacr12345prod
  TF_VAR_resource_group_name: nausicaas-rg

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Azure login via OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ env.ARM_CLIENT_ID }}
          tenant-id: ${{ env.ARM_TENANT_ID }}
          subscription-id: ${{ env.ARM_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.2

      - name: Terraform Init
        working-directory: infrastructure/terraform
        run: terraform init

    #TEMPORARY - Adding state cleanup step to remove RG + ACR from Terraform state to unblock subsequent runs. This is needed because the RG + ACR were manually deleted outside of Terraform, and thus are now in a "tainted" state in Terraform.   
      - name: TEMP - State cleanup (remove RG + ACR from Terraform state)
        working-directory: infrastructure/terraform
        run: |
          echo "State BEFORE cleanup:"
          terraform state list || true

          terraform state rm azurerm_resource_group.main || true
          terraform state rm azurerm_container_registry.acr || true

          echo "State AFTER cleanup:"
          terraform state list || true

      - name: Terraform Plan
        if: github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && (github.event.inputs.action == 'plan' || github.event.inputs.action == 'apply'))
        working-directory: infrastructure/terraform
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        if: github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'apply')
        working-directory: infrastructure/terraform
        run: terraform apply -auto-approve tfplan

      - name: Terraform Destroy
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'destroy'
        working-directory: infrastructure/terraform
        run: terraform destroy -auto-approve